# Generated by Django 3.2.9 on 2022-02-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20211223_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='uuid',
        ),
    ]
