# Generated by Django 3.2.9 on 2022-02-20 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questions_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
